#!/usr/bin/env bash

RED="\033[31m"
GREEN="\033[32m"
YELLOW="\033[33m"
TEXT="\033[0;39m"
_BOLD=$(tput bold)
_NORMAL=$(tput sgr0)
DATA_DIR="$HOME/.local/share/wpman/wpman_data"

case $1 in
    -h | --help)
        echo -e "usage:\nwpman [flags] [arguments]"
        ;;

    -Ss)
        if [ $2 ]
        then
            if [ -d $DATA_DIR/$2.txt ]
            then
                echo -e "searching database...\n" ; sleep 0.1
                cat $DATA_DIR/$2.txt | while read name; do
                    echo "$name"
                done
            else
                echo -e "${YELLOW}${_BOLD}ERROR:${TEXT}${_NORMAL} $2 does not exist."
                exit 1
            fi
        else
            echo -e "\n${YELLOW}${_BOLD}ERROR:${TEXT}${_NORMAL} input expected after \"-Ss\"."
            exit 1
        fi
        ;;

esac
